### ISSUE TITLE
Handling of named terms

### ISSUE THREAD

**Issue by Stevendeo** [Gbury/dolmen#187]
I am searching how to access the custom names of assertions (and sub expressions). For example, on the following file:
```
(set-logic ALL)
(declare-const x Int)
(assert (! (= x (! (+ x x) :named foo)) :named bar))
```
I would like to have the term `+ x x` associated to the identifier `foo` and the whole assertion associated to the identifier `bar`.

**Comment by Gbury** [comment]
Closing since #199 has been merged.
