### ISSUE TITLE
smtlib parsing: assertion hit when parsing wrongly typed equation

### ISSUE THREAD

**Issue by quicquid** [Gbury/dolmen#26]
Please consider the following smtlib script:

```
(set-logic AUFLIA)
(declare-fun notindomain (Int) Int)
(assert (forall ((i Int))
                (= (notindomain i) (or (< i 0) (< 5 i)) )))
(check-sat)
```

It contains a type error because notindomain should be of type Int to Bool. When I run dolmen on the file, I receive the following error message:

```
Error While typing: (= (notindomain (i)) (or (< (i) 0) (< 5 (i))))
File '/tmp/test.smt2', line 6, character 16-57:
The term: (Fatal error: exception File "src/standard/expr.ml", line 484, characters 6-12: Assertion failed
```

The error occurs in pretty printing (the assertion requires an infix operator to have at least 2 arguments) so it might hide the actual error.

**Comment by Gbury** [comment]
This was solved by PR#27 but apparently github didn't automatically close the issue, ^^
