### ISSUE TITLE
Comments for suppression

### ISSUE THREAD

**Issue by andrewvaughanj** [Gbury/dolmen#83]
I'm interested in using Dolmen alongside a test-case reducer such as [`ddSMT`](https://github.com/ddsmt/ddSMT) or [`cvise`](https://github.com/marxin/cvise). However, what I'm *really* interested in is in making sure that the reduction process does not make things *any worse* than when they started.

This ability to suppress warnings (in the input file) would match what typical code-based static analysers allow us to do.

For example, consider a file such as:

```
(set-logic QF_UFLIA)
(declare-fun fmt0 () Int)
(declare-fun fmt1 () Int)
(declare-fun s_count (Int) Int)
(assert (>= (* 4 (s_count (+ (- 2) (* (- 1) fmt0) fmt1))) 0))
(check-sat)
(exit)
```

which gives:

```
File "./suppress.smt2", line 5, character 12-57:
Error This is a non-linear expression according to the smtlib spec.
      Hint: multiplication in strict linear arithmetic expects an integer or
        rational literal and a symbol (variable or constant) but was given:
        - an integer coefficient
        - an arbitrary expression with top symbol not in Arithmetic
```

I would like the ability to make Dolmen *not* report on this error, if I do something like:

```
(set-logic QF_UFLIA)
(declare-fun fmt0 () Int)
(declare-fun fmt1 () Int)
(declare-fun s_count (Int) Int)
; dolmen-no-error
(assert (>= (* 4 (s_count (+ (- 2) (* (- 1) fmt0) fmt1))) 0))
(check-sat)
(exit)
```

Or something similar.

I think to *actually* make this useful, the errors that come from Dolmen need to have some kind of "unique identifier", such that you can silence *particular* warnings (e.g., with gcc can you do things like `-Wno-unused`).

For example, the above might be:

```
; dolmen-no-error[non-linear]
```

or

```
; dolmen-no-error[dol123]
```

where `dol123` is some identifier that Dolmen gives to "This is a non-linear expression according to the smtlib spec".

It is then up to the minimiser to know if it can/can't remove something -- for example, the reducer might simplify Line 5 such that the comment can *then* be removed. It has a weakness that the minimiser might "squash lines together" to get them to avoid errors, but /c'est la vie/.

**Comment by Gbury** [comment]
With the number of warning increasing I've already been thinking about a way to turn some warnings on/off, à la GCC, so it seems like it's the right time to do it, ^^
To be more precise, I plan to add unique identifiers to dolmen errors and warnings, as well as the ability to silence warnings form the command line and from dedicated comments inside source files, and the ability to make some warnings fatal (which effectively turns them into errors).

**Comment by andrewvaughanj** [comment]
I think the ability to do something like:

- `-Wno-<something>`
- `-Werror=<something>`
- and comment suppression

sounds wonderful (and will work perfectly for my use-case!).

When I'm reducing C/C++, I typically just do `-Wno-<msg>` rather than adding comments; so having a `-Wno-<something>` equivalent in Dolmen would be really wonderful!

For example, `ddSMT` will happily remove the `(set-logic:`, so it would be great to use Dolmen to enforce not removing that.

**Comment by Gbury** [comment]
I have opened #84 which adds cli options to control warnings.

> For example, `ddSMT` will happily remove the `(set-logic:`, so it would be great to use Dolmen to enforce not removing that.

Note that `dolmen` already requires smtlib files to contain a `set-logic` statement currently (i.e. it's an error for an smtlib file to have no `set-logic` statement, and errors cannot be turned on/off).

**Comment by Gbury** [comment]
@andrewvaughanj ping 

Now that #84 is merged, you can finely control the warnings that are emitted by Dolmen, using command line options.

For you original example, you can now do

```
dolmen --warn=-almost-linear-expr <some_file>
```

and it will disable the warning about almost linear expressions (which is a fatal warning by default).

I'll now close this issue, and keep in mind that at one point we might want inline file annotations one day to control warnings.
