### ISSUE TITLE
Typo in smtlib grammar

### ISSUE THREAD

**Issue by anmaped** [Gbury/dolmen#9]
```
function_def:
  | s=SYMBOL OPEN args=sorted_var* CLOSE ret=sort body=term CLOSE
{ I.(mk term s), args, ret, body }
```

The last `CLOSE` is a typo. It should be removed.

**Comment by Gbury** [comment]
You're right, I'll fix that. By the way, would you have some files on which dolmen fails currently because of this typo ? I could add them to the testsuite ( https://github.com/Gbury/dolmen/tree/master/tests/smtlib ).

**Comment by anmaped** [comment]
Yes. You could use these examples:
```
(declare-datatypes () ((Threevalue (TVTRUE) (TVFALSE) (TVUNKNOWN) )))
(define-fun tvnot ((phi Threevalue)) Threevalue
	(ite (= phi TVTRUE) TVFALSE (ite (= phi TVFALSE) TVTRUE TVUNKNOWN) )
)
```

```
(declare-datatypes () ((Threevalue (TVTRUE) (TVFALSE) (TVUNKNOWN) )))
(define-fun tvor ((phi1 Threevalue) (phi2 Threevalue)) Threevalue
	(ite (or (= phi1 TVTRUE) (= phi2 TVTRUE) ) TVTRUE (ite (and (= phi1 TVFALSE) (= phi2 TVFALSE)) TVFALSE TVUNKNOWN ) )
)
```

By the way, I also noted that comments in smtlib are not allowed by the parser.

**Comment by Gbury** [comment]
Closed with the last commits. Note that the files in your last comment are not valid in smtlib v2.6 because of the datatype declaration (see https://github.com/Gbury/dolmen/blob/master/tests/smtlib/test-fun_def_1.smt2 for instance).

**Comment by anmaped** [comment]
Yes. It's right. They are v2.5.
